apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  index.html: |
    <html>
      <body>
        <h1>Hello from ConfigMap!</h1>
      </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: hello-config

---
apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-svc
spec:
  selector:
    app: hello-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
